### ISSUE TITLE
Typo in https://github.com/brenns10/brenns10.github.io/blob/master/_posts/2020-05-08-meson.md

### ISSUE THREAD

**Issue by RonKaminsky** [brenns10/brenns10.github.io#2]
Hi, thanks for the interesting blog post!

In https://github.com/brenns10/brenns10.github.io/blob/master/_posts/2020-05-08-meson.md :

There's a typo in the title of the section: "Embracing cosistent tooling" ...

Hmm, if I'm here, I might as well check the whole thing, so also: "embarassment" -> "embarrassment"

**Comment by brenns10** [comment]
Thanks for pointing this out! I've updated the text accordingly.
